apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3647m
              memory: 2362Mi
            requests:
              cpu: 1823m
              memory: 1817Mi

