apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3659m
              memory: 2918Mi
            requests:
              cpu: 1829m
              memory: 2244Mi

