apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3657m
              memory: 3038Mi
            requests:
              cpu: 1828m
              memory: 2337Mi

