apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        resources:
          limits:
            cpu: 3662m
            memory: 2908Mi
          requests:
            cpu: 1831m
            memory: 2237Mi
