apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3630m
              memory: 2942Mi
            requests:
              cpu: 1815m
              memory: 2263Mi

