apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3645m
              memory: 2412Mi
            requests:
              cpu: 1822m
              memory: 1855Mi

