apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3667m
              memory: 2917Mi
            requests:
              cpu: 1833m
              memory: 2244Mi

