apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3672m
              memory: 2906Mi
            requests:
              cpu: 1836m
              memory: 2235Mi

