apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 2444m
              memory: 3828Mi
            requests:
              cpu: 977m
              memory: 2945Mi
