apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        resources:
          limits:
            cpu: 3224m
            memory: 2397Mi
          requests:
            cpu: 1612m
            memory: 1844Mi
