apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3674m
              memory: 2927Mi
            requests:
              cpu: 1837m
              memory: 2251Mi

