apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 4468m
              memory: 2928Mi
            requests:
              cpu: 2234m
              memory: 2252Mi

