apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3677m
              memory: 2911Mi
            requests:
              cpu: 1838m
              memory: 2239Mi

