apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3651m
              memory: 2716Mi
            requests:
              cpu: 1825m
              memory: 2089Mi

