apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3637m
              memory: 2785Mi
            requests:
              cpu: 1818m
              memory: 2142Mi

