apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 4432m
              memory: 2371Mi
            requests:
              cpu: 2216m
              memory: 1824Mi

