apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3639m
              memory: 2800Mi
            requests:
              cpu: 1819m
              memory: 2153Mi

