apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 2055m
              memory: 1194Mi
            requests:
              cpu: 822m
              memory: 919Mi
