apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 2013m
              memory: 3549Mi
            requests:
              cpu: 1006m
              memory: 2730Mi
