apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 2386m
              memory: 3299Mi
            requests:
              cpu: 954m
              memory: 2538Mi
