apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 2044m
              memory: 2929Mi
            requests:
              cpu: 1022m
              memory: 2253Mi
