apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3641m
              memory: 2916Mi
            requests:
              cpu: 1820m
              memory: 2243Mi

