apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 2468m
              memory: 3670Mi
            requests:
              cpu: 987m
              memory: 2823Mi
