apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3632m
              memory: 2922Mi
            requests:
              cpu: 1816m
              memory: 2247Mi

