apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        resources:
          limits:
            cpu: 3673m
            memory: 1924Mi
          requests:
            cpu: 1836m
            memory: 1480Mi
