apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3656m
              memory: 2890Mi
            requests:
              cpu: 1828m
              memory: 2223Mi

