apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 2038m
              memory: 3335Mi
            requests:
              cpu: 1019m
              memory: 2566Mi
