apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3650m
              memory: 2899Mi
            requests:
              cpu: 1825m
              memory: 2230Mi

