apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
        - name: hello-world
          resources:
            limits:
              cpu: 3655m
              memory: 2861Mi
            requests:
              cpu: 1827m
              memory: 2200Mi

