apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    spec:
      containers:
      - name: hello-world
        resources:
          limits:
            cpu: 3669m
            memory: 2914Mi
          requests:
            cpu: 1834m
            memory: 2242Mi
