environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 6547m
    memory: 953Mi
  requests:
    cpu: 3273m
    memory: 733Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 