environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5681m
    memory: 1981Mi
  requests:
    cpu: 2840m
    memory: 1524Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 