autoscaling:
  enabled: true
  maxReplicas: 6
  minReplicas: 3
environment: production
image:
  pullPolicy: IfNotPresent
  repository: polinux/stress-ng
  tag: latest
replicaCount: 3
resources:
  limits:
    cpu: 5658m
    memory: 2190Mi
  requests:
    cpu: 2829m
    memory: 1684Mi
