environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5703m
    memory: 2187Mi
  requests:
    cpu: 2851m
    memory: 1682Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 