environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5668m
    memory: 2213Mi
  requests:
    cpu: 2834m
    memory: 1702Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 