environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2178m
    memory: 1269Mi
  requests:
    cpu: 1089m
    memory: 976Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 
