environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5693m
    memory: 2174Mi
  requests:
    cpu: 2846m
    memory: 1672Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 