autoscaling:
  enabled: true
  maxReplicas: 6
  minReplicas: 3
environment: production
image:
  pullPolicy: IfNotPresent
  repository: polinux/stress-ng
  tag: latest
replicaCount: 3
resources:
  limits:
    cpu: 5687m
    memory: 2189Mi
  requests:
    cpu: 2843m
    memory: 1683Mi
