environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "v0.15.10"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1000m    # 1 full CPU core
    memory: 768Mi # 3x the VM stress amount for headroom
  requests:
    cpu: 400m     # 40% of limit - allows for bursting
    memory: 384Mi # 50% of limit - good starting point

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6

command: ["/usr/bin/stress-ng"]

args:
  - "--cpu"
  - "2"
  - "--cpu-method"
  - "matrixprod"
  - "--cpu-load"
  - "60"
  - "--vm"
  - "2"
  - "--vm-bytes"
  - "256M"
  - "--timeout"
  - "0"
  - "--metrics-brief"
  - "--cpu-load-slice"
  - "25"
  - "--cpu-method-switch"
  - "60" 