environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5684m
    memory: 1677Mi
  requests:
    cpu: 2842m
    memory: 1290Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 