environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4345m
    memory: 3771Mi
  requests:
    cpu: 2172m
    memory: 2900Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 
