environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5709m
    memory: 2177Mi
  requests:
    cpu: 2854m
    memory: 1674Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 