environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2860m
    memory: 4288Mi
  requests:
    cpu: 1430m
    memory: 3299Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 
