environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4542m
    memory: 2064Mi
  requests:
    cpu: 2271m
    memory: 1587Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 