environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5669m
    memory: 2175Mi
  requests:
    cpu: 2834m
    memory: 1673Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 