autoscaling:
  enabled: true
  maxReplicas: 6
  minReplicas: 3
environment: production
image:
  pullPolicy: IfNotPresent
  repository: polinux/stress-ng
  tag: latest
replicaCount: 3
resources:
  limits:
    cpu: 5625m
    memory: 2187Mi
  requests:
    cpu: 2812m
    memory: 1682Mi
