environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5724m
    memory: 2248Mi
  requests:
    cpu: 2862m
    memory: 1729Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 