environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5645m
    memory: 2272Mi
  requests:
    cpu: 2822m
    memory: 1748Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 