environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5713m
    memory: 2212Mi
  requests:
    cpu: 2856m
    memory: 1701Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 