environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5695m
    memory: 1821Mi
  requests:
    cpu: 2847m
    memory: 1401Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 