autoscaling:
  enabled: true
  maxReplicas: 6
  minReplicas: 3
environment: production
image:
  pullPolicy: IfNotPresent
  repository: polinux/stress-ng
  tag: latest
replicaCount: 3
resources:
  limits:
    cpu: 5177m
    memory: 1509Mi
  requests:
    cpu: 2588m
    memory: 1160Mi
