environment: production

replicaCount: 3

image:
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6

command: 
  - stress-ng

args:
  - "--cpu"
  - "1"
  - "--vm"
  - "1"
  - "--vm-bytes"
  - "256M"
  - "--timeout"
  - "0"
  - "--metrics-brief" 