environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5717m
    memory: 1715Mi
  requests:
    cpu: 2858m
    memory: 1319Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 