environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2968m
    memory: 4742Mi
  requests:
    cpu: 1484m
    memory: 3647Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 
