environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 3052m
    memory: 4856Mi
  requests:
    cpu: 1526m
    memory: 3735Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 
