autoscaling:
  enabled: true
  maxReplicas: 6
  minReplicas: 3
environment: production
image:
  pullPolicy: IfNotPresent
  repository: polinux/stress-ng
  tag: latest
replicaCount: 3
resources:
  limits:
    cpu: 5634m
    memory: 2202Mi
  requests:
    cpu: 2817m
    memory: 1694Mi
