environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 3033m
    memory: 5351Mi
  requests:
    cpu: 1516m
    memory: 4116Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 
