environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2077m
    memory: 1384Mi
  requests:
    cpu: 1038m
    memory: 1065Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 
