environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 2863m
    memory: 3847Mi
  requests:
    cpu: 1431m
    memory: 2959Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 
