environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5699m
    memory: 1929Mi
  requests:
    cpu: 2849m
    memory: 1484Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 