environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5687m
    memory: 1664Mi
  requests:
    cpu: 2843m
    memory: 1280Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 