environment: production

replicaCount: 3

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 5682m
    memory: 2090Mi
  requests:
    cpu: 2841m
    memory: 1607Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6 