environment: staging

replicaCount: 2

image:
  repository: polinux/stress-ng
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    cpu: 750m
    memory: 512Mi
  requests:
    cpu: 300m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4 