apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-staging
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: hello-world
  source:
    path: examples/kustomize/hello-world/overlay/staging
    repoURL: 'https://github.com/h-c-a/argocd-stub-repo'