apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: polinux/stress-ng:latest
          command: ["/bin/stress-ng"]
          args: 
            - "--cpu"
            - "2"
            - "--cpu-method"
            - "matrixprod"
            - "--cpu-load"
            - "60"
            - "--vm"
            - "2"
            - "--vm-bytes"
            - "256M"
            - "--timeout"
            - "0"
            - "--metrics-brief"
            - "--cpu-load-slice"
            - "25"
            - "--cpu-method-switch"
            - "60"