apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world-chart.fullname" . }}
  labels:
    {{- include "hello-world-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-world-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hello-world-chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            - stress-ng
          args:
            - "--cpu"
            - "1"
            - "--vm"
            - "1"
            - "--vm-bytes"
            - "256M"
            - "--timeout"
            - "0"
            - "--metrics-brief"
          resources:
            {{- toYaml .Values.resources | nindent 12 }} 