apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-helm-world-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/h-c-a/argocd-stub-repo'
    path: helm/hello-world
    helm:
      valueFiles:
        - environments/production.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-world-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 